### ISSUE TITLE
Dependency not listed in README

### ISSUE THREAD

**Issue by m5w** [matxin/matxin#9]
Matxin also requires libboost-system-dev. I'm not sure what version it requires, though.

**Comment by ftyers** [comment]
It shouldn't need it now. Can you try removing it and see if it still works.

**Comment by m5w** [comment]
It certainly needs it during configuration (see https://github.com/matxin/matxin/blob/master/configure.ac#L319), but I don't think any of the code actually needs Boost System.

Update: I can confirm Matxin does indeed compile without any Boost libraries or headers installed (even libboost-program-options-dev, despite this include: https://github.com/matxin/matxin/blob/master/src/config.h#L34). The solution should be as simple as removing line 319 from configure.ac.
